title: <p align="center"> Rohan Sen </p>
logo: /assets/img/images.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rohan-sen-56b0a1127/">LinkedIn</a> |
  <a href="https://github.com/Rohan1628">GitHub</a>
  
  <br>   
  I'm working as a Python Developer having good experience with AWS. 
  I build chatbots and automations for Autodesk.
  Doing Masters in AI and ML to make these chatbots intelligent.
  <br>
  </p>



theme: jekyll-theme-minimal
